version: '3.7'
services:
  kuchapa-api:
    image: 'kuchapa_api_container:${IMAGE_TAG}'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kuchapa-api
    command: node server.js
    volumes:
      - ./:/Kuchapa_backend
      - kuchapa-api-node_modules:/Kuchapa_backend/node_modules
    ports:
      - '4000:4000'
    networks:
      - app-network
volumes:
  kuchapa-api-node_modules:
networks:
  app-network:
    driver: bridge
